### Test the /bfhl endpoint with Example A data

POST http://localhost:3000/bfhl
Content-Type: application/json

{
  "data": ["a","1","334","4","R", "$"]
}

###
### Test with Example B data

POST http://localhost:3000/bfhl
Content-Type: application/json

{
    "data": ["2","a", "y", "4", "&", "-", "*", "5","92","b"]
}